### ISSUE TITLE
V2_0_4 'PassPumpGUI_v2_0.py' incorrect file uploaded

### ISSUE THREAD

**Issue by JSField** [seawarrior181/PasswordPump_II#1]
Hello. The v2_0_4 version of the file 'PassPumpGUI_v2_0.py' is actually the .ino file.

**Comment by seawarrior181** [comment]
JSField,

Thanks for pointing that out!  I fixed it just now.  Let me know how it's going and if you run into any problems.  I'm not sure if you have a kit, maybe you're just trying to determine if the python program runs for you.

Best,
Dan

**Comment by JSField** [comment]
I don't have a kit yet, but I signed up for notification when they are back in stock. Originally saw your v1.0 Instructable, and have been looking forward to your v2.0! Looks like you have made a lot of improvements. 
Thanks,
Jeff

**Comment by seawarrior181** [comment]
Hi Jeff,

As soon as I get some feedback from the first 10 kits I sent out I'll post the inventory for the next 10 and you'll get notified.  I don't want to sell more kits until I'm confident that folks are not having problems.  If you see anything else that needs improvement please let me know.  Thanks for the interest!  I use it every day all day long and it's working great for me.

Best,
Dan
