### ISSUE TITLE
Unable to locate 4K7 ohm PCBs

### ISSUE THREAD

**Issue by Zpmqwertyuiop** [seawarrior181/PasswordPump_II#13]
I can't find the 4k7 ohm PCB in the folder with path "PasswordPump_II-master\Hardware\v2_0_8", all the PCBs in there don't have 4k7 ohm, did you put the wrong file? Where should I find the PCBs with 4k7 ohms?

**Comment by seawarrior181** [comment]
The 4k7 ohm resistors are unnecessary and do not appear on the PCB files after v2_0_4.

**Comment by Zpmqwertyuiop** [comment]
Okay,thank you for your amswer.

**Comment by seawarrior181** [comment]
You're welcome!
