### ISSUE TITLE
.bin file in 2_0_5 is incorrect

### ISSUE THREAD

**Issue by JSField** [seawarrior181/PasswordPump_II#3]
The .bin file in the root directory is actually v2_0_4. The correct .bin file is in the 'bin' folder is correct though.

**Comment by seawarrior181** [comment]
Hi JSField,

Thanks for reporting this, however it is intentional.  I prefer for folks to use the 2.0.4 release for now. 

Best,
Dan Murphy
dan-murphy@comcast.net
5volts.org

**Comment by seawarrior181** [comment]
JSField, do you mean to say that PasswordPump_II/v2_0_5/PasswordPump_v_2_0.ino.bin is actually 2.0.4?  Thanks, I will take care of it.
