### ISSUE TITLE
Output from PasswordPump is changed from caps to lower and vice versa

### ISSUE THREAD

**Issue by JSField** [seawarrior181/PasswordPump_II#5]
Not sure if this something that happens because of the way you send the keyboard input. If you have Caps lock on, all Caps letters are changed to lower case and all lower case are changed to Caps. This happens with anything sent from the device.

**Comment by seawarrior181** [comment]
Hi Jeff, thanks for the information.  I will add that to the Users Guide.  That's just the way it's always worked and as far as I know I have no control over it.  It's annoying when you're trying to login and the caps lock is down, just like when you're trying to login without the PasswordPump.  AFAIK there is no way for me to detect if the caps lock is engaged, so there is no way for me to reverse the case of the input to the computer.

Best,

Dan Murphy
dan-murphy@comcast.net
5volts.org

**Comment by seawarrior181** [comment]
The troubleshooting section of the Users Guide has been updated to reflect this problem.  Thanks Jeff.
