### ISSUE TITLE
suggestions for assembly instructions

### ISSUE THREAD

**Issue by wjcarpenter** [seawarrior181/PasswordPump_II#7]
Thanks for going to the trouble of making this device. I was thinking of making something similar when I discovered your device on Tindie.

I just assembled 2 PasswordPump II devices from kits. In general, I found the assembly instructions excellent, and assembly is pretty easy for anybody with any soldering experience. Following are some suggestions/feedback on the assembly process. Everybody has their own favorite ways of doing things, so no offense taken if you choose to ignore these.

1. I wouldn't even bother with this first suggestion, except that your assembly instructions seem to want to help less experienced people. All of the pin headers used get assembled in what most people think of as "the normal way". If someone is less experienced, they might accidentally insert them in one of the three less common possibilities. Spacing is kind of critical for this kit due to vertical stacking, so you might want to be explicit about how to insert the pin headers. [Clarifying ... The usual header pins have a short end and a long end with a plastic spacer separating them. (You can actually slide the spacer around, but let's ignore that for this discussion.) The "usual way" is to insert the short end of the header from the bottom of the board and solder it on the top side of the board. Other ways would be to insert the long end form the bottom, insert the long end from the top, insert the short end from the top. Once the pin headers are inserted, there is only one choice about which side of the board takes the solder. Those other orientations are unusual, but they can be used for some special situations. So, for beginners, it would be helpful to say something like "The pin headers get the short end inserted from the bottom of the board, and then they are soldered in place on the top side of the board." Or, maybe that's overburdening the explanation. :-)]

2. I would attach the rotary encoder and maybe even the RGB LED as the last soldered components. The stem from the rotary encoder sticks up quite a bit and makes working on the back side of the board a little unstable if you don't have a good helping hands holder of some kind. As far as I can tell, saving them for later would not be any kind of assembly problem.

3. It's no surprise to anybody to say that mounting the display board is a little fiddly. There is a surface mount IC on the back of the display that really, really wants to push the reset button on the Itsy Bitsy. It's hard to hold everything in the right position to solder the display board pins in place while avoiding that reset pin and also getting a cosmetically good position for the display board. I used a different technique to mount mine (after desoldering my first miserable attempt).

- It's easy to remove the cap/plunger from the Itsy Bitsy reset button. (In fact, I was surprised how easy it was.) Using fine-nosed pliers, lift off the metal cap that holds the black button. Under that are 1 or 2 circular layers. Remove those, too. You should be left with 3 contact pads exposed from the internals of the switch. There will also be some tiny pieces of structural plastic and, of course, the solder tabs for the switch; it's OK to leave all that in place. With the switch deconstructed like that, it's nearly impossible to accidentally reset the Itsy Bitsy that way. That doesn't matter since you put an alternate reset button on the back of the main PCB.

- I used the rubber band trick given in the instructions to hold the display board against the top of the micro USB connector on the Itsy Bitsy. In other words, I put the rubber band on the end of the display board instead of the center. On the other end of the display board, I used a scrap piece of thick wire as a temporary spacer. That made it easy to see that the display board was level and straight. The rubber band keeps things from shifting.

- After soldering the display board pins on the back side of the main PCB, I removed the scrap wire spacer from under the display board by simply pulling it out. The result was perfect, and it was an easy process for getting good results.

**Comment by seawarrior181** [comment]
Mr. Carpenter,

Thanks for taking the time to write up all of that feedback.  I will work it in the next time I'm taking pictures of the assembly process.  We have independently come to the same conclusions with respect to a couple of these suggestions, especially with respect to the order of assembly and the technique for attaching the display.

Best,

Dan Murphy

**Comment by FleshdeckTV** [comment]
Hello, In terms of functionality, there is not enough setting for the length of the generated password, in some cases the password length of 31 characters is too long, can you add such functionality? Аnd I also saw that the firmware mentions different memory chips, 256, 512, 1024, but 512 is used, is it possible to use chips other than 512?

**Comment by seawarrior181** [comment]
Yes it is possible to add a feature to the PasswordPump device whereby the length of the generated password can be specified as a setting.  I will take this suggestion into consideration.  You can also generate passwords in the PasswordPumpGUI, where it also generates a 31 character password, but of course you can easily make it any size you like with the backspace key.

It is not possible to substitute a chip other than the 25LC512 EEprom.  To allow for such functionality in the program is possible, however I don't think it's a high priority because the 25LC512 provides for enough room to store 250 sets of credentials, which is more than enough for most people.

Thanks for your interest.

Best,
Dan

**Comment by seawarrior181** [comment]
FleshDeckTV,

Today I enhanced the PasswordPump device by adding to it the ability to specify the default generated password size under the Settings menu; 8, 10, 16, 24 or 31.  The code is posted in v2_0_6.

Best,
Dan

**Comment by seawarrior181** [comment]
RE: Mr. Carpenter, on suggestion #1; now understood, thank you very much for the clarification.  The User's Guide was updated.

Dan
