### ISSUE TITLE
feature suggestion: TOTP MFA

### ISSUE THREAD

**Issue by wjcarpenter** [seawarrior181/PasswordPump_II#8]
This is a suggestion for a future feature.

What if PP could supply the 6-digit one-time codes that are used for multi-factor authentication? I got this idea from the Bitwarden password manager; after filling in credentials for an MFA-enabled account, it automatically copies the current 6-digit code to the clipboard for easy pasting. With PP, instead of copying to the clipboard, it would just be another field that could be supplied like username and password, with some kind of style for tabs, CRs, etc.

You probably already know that those 6-digit codes are a particular implementation of a standard called TOTP (time-based one-time passwords). People usually think of this as "the Google authenticator app", but there are many others that work with the same algorithm. Code to implement TOTP is not very difficult, and there are plenty of open source sample implementations around.

As the name implies, the tokens are time-based, which means the codes are created by a straightforward calculation based on a shared secret and the current timestamp. As mostly a simple keyboard emulator, PP doesn't care what time it is, but I believe the chip on the Itsy Bitsy does contain a real-time clock. Perhaps the PP GUI application could be enhanced to tell the PP device what the current time is. Obviously, the RTC would lose the time awareness when power is removed, but it would still be useful for those who leave the PP device plugged into USB most of the time. (A future hardware revision of the PP might have a coin cell battery to power the RTC, but the feature doesn't require it.)

Another difficulty with TOTP is that it requires a site-specific seed value called the authenticator key (a shared secret). The seed is encoded into those QR codes that can be scanned by a smart phone, but there is also a plain-text version of what is encoded in the QR code. Most apps that deal with TOTP will let you either scan the QR code or enter the plain-text seed manually (but once they have it, they are not interested in giving it back to you, which is annoying). The PP GUI could allow for entry of that plain-text seed. It could also be entered via the rotary encoder, but the text form of the seed is pretty long.

There's a theoretical argument that you would be defeating the benefit of MFA by doing having this feature since it would be storing the permanent password and the seed for the TOTP in the same device. The typical definition of MFA is "something you know and something you have". If you are using randomly generated passwords with a hardware or software password manager, which you should, then you already don't know the password. You are, in a sense, delegating things so that the "something you know" is the master password for the password manager. So, you haven't lost anything by also putting the TOTP in the password manager. (And, hey, if you're worried about it, just use two different PasswordPumps :-)).

**Comment by wjcarpenter** [comment]
The TOTP algorithm is documented in https://tools.ietf.org/html/rfc6238. It includes a reference implementation in Java. This wikipedia article gives a short overview: https://en.wikipedia.org/wiki/Google_Authenticator. Once you know the right jargon terms to search for, you can find other open source implementations. The code for Google's implementation is here: https://github.com/google/google-authenticator

The spec includes a couple of options for variations. If anything is a bother to implement, you could get by with using the selections that the Google Authenticator app uses since that's what most web sites use.

**Comment by seawarrior181** [comment]
Mr. Carpenter,

Thanks for the insightful suggestion.  I will keep this idea in mind for the future.  I really appreciate all the effort you invested in writing up this detailed suggestion.

Best,
Dan
