### ISSUE TITLE
Option to slow down keypress signals, for use when inputting to a tablet

### ISSUE THREAD

**Issue by scootercommuter** [seawarrior181/PasswordPump_II#9]
I suggest adding the ability to send keypress signals more slowly, as an on/off option.  We tried using the Password Pump with our Samsung tablet, using a USB-to-micro USB conversion cable.  The tablet was able to power the Password Pump and it will accept USB input, but it looked as if the input from the Password Pump was coming in too fast for the tablet to recognize all the characters -- it dropped quite a few.  I expect that if it were possible to slow down the sending of characters (Tablet, or Slow-Type mode?) we could use the Pump with the tablet.  Not a deal breaker for sure, we just won't use the tablet for any web sites where we're concerned about login security.

**Comment by seawarrior181** [comment]
Thanks for the feedback.  I've noticed this too and it's on the list.  

-Dan

**Comment by seawarrior181** [comment]
Hi,

I'm working on this functionality this weekend and hope to release it to 2.0.6 soon.

Best,
Dan

**Comment by seawarrior181** [comment]
Added a setting that allows for the introduction of delay between the transmission of each character to the computer/tablet/phone so that slower devices do not drop characters.  From the Settings menu select Inter Char Delay and select a delay of 0 (default), 10, 25, 100, or 250 milliseconds between the transmission of each character.  Available in the source and in the binary in the M0 folder (ItsyBitsy M0) under 2.0.6.  I'll place the M4 version of the binary in the morning.

**Comment by wjcarpenter** [comment]
FWIW, I've also noticed some bad password pushes on a intermittent basis. I wasn't clear on what was going on, but the issue in this thread makes sense. Indiana lot of work over remote connections, and it could be that they sometimes can't cope with rapid fire "typing".

I'm glad you've already implemented the delay thing.

**Comment by scootercommuter** [comment]
I applied the latest upload of 2.6 M0, and IT WORKS when using the Password Pump with our Samsung tablet!  I set the character delay to 100, which is a little slow for general use but acceptable (but faster than most people can type), and we're able to send our credentials on both the desktop and the tablet.  Thanks!

**Comment by seawarrior181** [comment]
Remember to also download the latest version of PasswordPumpGUI.  -Dan
